/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baksopuas;

/**
 *
 * @author Daffa Lintang
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputMenuBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        historiBtn = new javax.swing.JButton();
        karyawanBtn = new javax.swing.JButton();
        cetakBarcodeBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        histori = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        karyawan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cetakBarcode = new javax.swing.JPanel();
        ceteakBarccodePanel = new javax.swing.JPanel();
        inputDiskonBarcode = new javax.swing.JTextField();
        inputKodeBarcode = new javax.swing.JTextField();
        searchInputBarcode = new javax.swing.JTextField();
        saveBtnBarcode = new java.awt.Button();
        EditBtnBarcode = new java.awt.Button();
        hapusBtnBarcode = new java.awt.Button();
        cariBtnBarcode = new java.awt.Button();
        kodeBarcode = new javax.swing.JLabel();
        diskonBarcode = new javax.swing.JLabel();
        jScrollPaneBarcode = new javax.swing.JScrollPane();
        barcodeTabel = new javax.swing.JTable();
        barcodeNav = new javax.swing.JPanel();
        barcodeNavLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideBar.setBackground(new java.awt.Color(255, 222, 197));
        sideBar.setPreferredSize(new java.awt.Dimension(130, 510));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(80, 80, 80));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 80));
        jLabel1.setText("BAKSO PUAS");
        sideBar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        inputMenuBtn.setBackground(new java.awt.Color(124, 183, 89));
        inputMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputMenuBtn.setText("Input Menu");
        inputMenuBtn.setBorder(null);
        inputMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMenuBtnActionPerformed(evt);
            }
        });
        sideBar.add(inputMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 40));

        logOutBtn.setBackground(new java.awt.Color(124, 183, 89));
        logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        sideBar.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, 40));

        homeBtn.setBackground(new java.awt.Color(124, 183, 89));
        homeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homeBtn.setText("Dashboard");
        homeBtn.setBorder(null);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        sideBar.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 40));

        historiBtn.setBackground(new java.awt.Color(124, 183, 89));
        historiBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        historiBtn.setText("Histori");
        historiBtn.setBorder(null);
        historiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiBtnActionPerformed(evt);
            }
        });
        sideBar.add(historiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 40));

        karyawanBtn.setBackground(new java.awt.Color(124, 183, 89));
        karyawanBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        karyawanBtn.setText("Karyawan");
        karyawanBtn.setBorder(null);
        karyawanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanBtnActionPerformed(evt);
            }
        });
        sideBar.add(karyawanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 40));

        cetakBarcodeBtn.setBackground(new java.awt.Color(124, 183, 89));
        cetakBarcodeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cetakBarcodeBtn.setText("Cetak Barcode");
        cetakBarcodeBtn.setBorder(null);
        cetakBarcodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakBarcodeBtnActionPerformed(evt);
            }
        });
        sideBar.add(cetakBarcodeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 40));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        mainPanel.add(dashboard, "card2");

        jLabel3.setText("Input Menu");

        javax.swing.GroupLayout inputMenuLayout = new javax.swing.GroupLayout(inputMenu);
        inputMenu.setLayout(inputMenuLayout);
        inputMenuLayout.setHorizontalGroup(
            inputMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputMenuLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel3)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        inputMenuLayout.setVerticalGroup(
            inputMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputMenuLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel3)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        mainPanel.add(inputMenu, "card3");

        jLabel4.setText("Histori");

        javax.swing.GroupLayout historiLayout = new javax.swing.GroupLayout(histori);
        histori.setLayout(historiLayout);
        historiLayout.setHorizontalGroup(
            historiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historiLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel4)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        historiLayout.setVerticalGroup(
            historiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historiLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        mainPanel.add(histori, "card4");

        jLabel5.setText("Karyawan");

        javax.swing.GroupLayout karyawanLayout = new javax.swing.GroupLayout(karyawan);
        karyawan.setLayout(karyawanLayout);
        karyawanLayout.setHorizontalGroup(
            karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel5)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        karyawanLayout.setVerticalGroup(
            karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(karyawanLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel5)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        mainPanel.add(karyawan, "card5");

        ceteakBarccodePanel.setBackground(new java.awt.Color(254, 239, 208));

        inputDiskonBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDiskonBarcodeActionPerformed(evt);
            }
        });

        inputKodeBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKodeBarcodeActionPerformed(evt);
            }
        });

        searchInputBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputBarcodeActionPerformed(evt);
            }
        });

        saveBtnBarcode.setLabel("Simpan");
        saveBtnBarcode.setName("Simpan"); // NOI18N

        EditBtnBarcode.setLabel("Edit");

        hapusBtnBarcode.setLabel("Hapus");

        cariBtnBarcode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cariBtnBarcode.setLabel("Cari");

        kodeBarcode.setForeground(new java.awt.Color(80, 80, 80));
        kodeBarcode.setText("Kode Barcode");

        diskonBarcode.setForeground(new java.awt.Color(80, 80, 80));
        diskonBarcode.setText("Diskon");

        javax.swing.GroupLayout ceteakBarccodePanelLayout = new javax.swing.GroupLayout(ceteakBarccodePanel);
        ceteakBarccodePanel.setLayout(ceteakBarccodePanelLayout);
        ceteakBarccodePanelLayout.setHorizontalGroup(
            ceteakBarccodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ceteakBarccodePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ceteakBarccodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diskonBarcode)
                    .addGroup(ceteakBarccodePanelLayout.createSequentialGroup()
                        .addComponent(inputKodeBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchInputBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ceteakBarccodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(ceteakBarccodePanelLayout.createSequentialGroup()
                            .addComponent(saveBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(EditBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapusBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(inputDiskonBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kodeBarcode))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        ceteakBarccodePanelLayout.setVerticalGroup(
            ceteakBarccodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ceteakBarccodePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(kodeBarcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ceteakBarccodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ceteakBarccodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputKodeBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchInputBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cariBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diskonBarcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDiskonBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ceteakBarccodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusBtnBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        barcodeTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Barcode", "Diskon", "Barcode"
            }
        ));
        barcodeTabel.setCellSelectionEnabled(true);
        jScrollPaneBarcode.setViewportView(barcodeTabel);

        barcodeNav.setBackground(new java.awt.Color(255, 186, 134));

        barcodeNavLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        barcodeNavLabel.setForeground(new java.awt.Color(255, 255, 255));
        barcodeNavLabel.setText("Cetak Barcode");

        javax.swing.GroupLayout barcodeNavLayout = new javax.swing.GroupLayout(barcodeNav);
        barcodeNav.setLayout(barcodeNavLayout);
        barcodeNavLayout.setHorizontalGroup(
            barcodeNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barcodeNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barcodeNavLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barcodeNavLayout.setVerticalGroup(
            barcodeNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barcodeNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barcodeNavLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cetakBarcodeLayout = new javax.swing.GroupLayout(cetakBarcode);
        cetakBarcode.setLayout(cetakBarcodeLayout);
        cetakBarcodeLayout.setHorizontalGroup(
            cetakBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetakBarcodeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(cetakBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ceteakBarccodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneBarcode))
                .addGap(23, 23, 23))
            .addComponent(barcodeNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cetakBarcodeLayout.setVerticalGroup(
            cetakBarcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetakBarcodeLayout.createSequentialGroup()
                .addComponent(barcodeNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ceteakBarccodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        mainPanel.add(cetakBarcode, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMenuBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(inputMenu);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_inputMenuBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(dashboard);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void historiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(histori);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_historiBtnActionPerformed

    private void karyawanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(karyawan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_karyawanBtnActionPerformed

    private void cetakBarcodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBarcodeBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(cetakBarcode);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_cetakBarcodeBtnActionPerformed

    private void inputDiskonBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDiskonBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDiskonBarcodeActionPerformed

    private void inputKodeBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKodeBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKodeBarcodeActionPerformed

    private void searchInputBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputBarcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button EditBtnBarcode;
    private javax.swing.JPanel barcodeNav;
    private javax.swing.JLabel barcodeNavLabel;
    private javax.swing.JTable barcodeTabel;
    private java.awt.Button cariBtnBarcode;
    private javax.swing.JPanel cetakBarcode;
    private javax.swing.JButton cetakBarcodeBtn;
    private javax.swing.JPanel ceteakBarccodePanel;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel diskonBarcode;
    private java.awt.Button hapusBtnBarcode;
    private javax.swing.JPanel histori;
    private javax.swing.JButton historiBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JTextField inputDiskonBarcode;
    private javax.swing.JTextField inputKodeBarcode;
    private javax.swing.JPanel inputMenu;
    private javax.swing.JButton inputMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneBarcode;
    private javax.swing.JPanel karyawan;
    private javax.swing.JButton karyawanBtn;
    private javax.swing.JLabel kodeBarcode;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel mainPanel;
    private java.awt.Button saveBtnBarcode;
    private javax.swing.JTextField searchInputBarcode;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
